Problem Statement 1

In [2]:
import numpy as np
np.vander([1,2,3,4])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [3]:
import numpy as np

In [4]:
def alex_theo_vande(input_vector,n,increasing=False):
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    return op_matx

In [8]:
input_vector = np.array([1,2,3,4,5])
no_col = 3
dec_order = alex_theo_vande(input_vector,no_col,False)
inc_order = alex_theo_vande(input_vector,no_col,True)
print(dec_order)


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [9]:
print(inc_order)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


Problem Statement 2


In [2]:
def moving_average(arr=None,window=None):
    n=len(arr)
    k=window
    result=[round(sum(arr[i:i+k])/k,2) for i in range(n-k+1)]
    
    for idx, val in enumerate(result):
        print(f"y{idx+1:02d} {val}")
    return result

In [5]:
arr2=[10,20,30,40,50,60,70,80,90,100]
result1=moving_average(arr=arr2,window=4)
print(result1)

y01 25.0
y02 35.0
y03 45.0
y04 55.0
y05 65.0
y06 75.0
y07 85.0
[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


In [7]:
arr3=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
result2=moving_average(arr=arr3,window=3)
print(result2)

y01 5.0
y02 4.67
y03 5.67
y04 6.67
y05 9.67
y06 28.67
y07 49.33
y08 72.67
y09 84.0
y10 93.33
y11 116.33
[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
